spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/physiocalendar
spring.datasource.username=physiouser
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080
jwt.secret=G9gH8g7eF6dJ4sK3rT2uV1wX0yZ9aB8cD7eF6gH5iJ4kL3mN2oP1qR0sT9uV8wX7y
jwt.expiration=86400000

